hmrc/ated-subscription-frontend

- app/views/contactDetailsEmail.scala.html
> ATED-3502 One change to the take of form-field from button

- app/views/appointAgent.scala.html
- app/views/contactDetails.scala.html
- app/views/correspondenceAddress.scala.html
- app/views/registeredBusinessAddress.scala.html
> ATED-3500 removed unneeded form groups

- app/views/subscription.scala.html
- public/javascript/subscription.js
> ATED-3478 Changed the disabled button on agent question

- public/stylesheets/ated-subscription.css
> ATED-3582 changed the red on the error input messages

- project/FrontendBuild.scala
> ATED-3605: update dependancy

- app/views/agentConfirmation.scala.html
- conf/messages
- test/controllers/AgentConfirmationControllerSpec.scala
> ATED-3727 CHANGES TO TITLE AND MERGED P INTO H1

- app/views/main.scala.html
> ATED-3830: Update page tag to display GOV.UK

- public/javascript/error-summary.js
> ATED-3876: Is this where we should send your client's letters about ATED?

- app/views/contactDetails.scala.html
- app/views/contactDetailsEmail.scala.html
- app/views/registeredBusinessAddress.scala.html
- conf/messages
- test/controllers/RegisteredBusinessControllerSpec.scala
> Ated 3874 company registered business address

- app/views/appointAgent.scala.html
- app/views/contactDetailsEmail.scala.html
- app/views/helpers/atedInputRadioGroupReveal.scala.html
- app/views/subscription.scala.html
- conf/messages
- public/javascript/show-hide-content.js
- public/javascript/subscription.js
- test/controllers/ContactDetailsEmailControllerSpec.scala
> ATED-3882: Add progressive reveal JS.

- app/views/contactDetailsEmail.scala.html
> ATED-3920: Fix issue with clearing out inputs with switching to no.

- conf/messages
Removed unused and duplicated message files
> DDCNLS 2821

- conf/messages
- test/controllers/CorrespondenceAddressControllerSpec.scala
- test/controllers/RegisteredBusinessControllerSpec.scala
- test/controllers/ReviewBusinessDetailsControllerSpec.scala
- test/controllers/SubscriptionControllerSpec.scala
@pankaj2453 - please can you check my code to make sure it's okay. 
CARE: do not merge until acceptance tests have been run.
> DDCNLS-3353 Replace apostrophes (unit tests updated)

- app/controllers/RegisterUserController.scala
Removed non utilised code in RegisterUserController that was affecting branch coverage
> DL-2124 Removed non utilised code

- app/connectors/TaxEnrolmentsConnector.scala
- test/connectors/TaxEnrolmentsConnectorSpec.scala
DL-2365 - Bug fix and test changes
- [ x  I've made every effort to commit high quality, clean code and I have executed relevant static analyses to be sure
> DL-2365 - bug fix and test changes

- app/config/ApplicationConfig.scala
- app/controllers/ApplicationController.scala
- app/views/unauthorisedAssistant.scala.html
- conf/app.routes
- conf/application.conf
- conf/messages
- project/FrontendBuild.scala
- project/MicroService.scala
- project/plugins.sbt
- test/controllers/ApplicationControllerSpec.scala
**Maintenance**
New content to improve guidance, supporting assistants who are unable to get through ATED subscription.
*Reviewee* (Chris)
*Reviewer* (Iyke)
Preview
> DL-2509 corrected guidance for organisation assistants

- app/config/ApplicationConfig.scala
- app/controllers/ApplicationController.scala
- app/controllers/auth/AtedSubscriptionAuthHelpers.scala
- app/utils/AuthUtils.scala
- app/views/unauthorisedAssistantAgent.scala.html
- app/views/unauthorisedAssistantOrg.scala.html
- conf/app.routes
- conf/application.conf
- conf/messages
- test/builders/AuthBuilder.scala
- test/controllers/ApplicationControllerSpec.scala
- test/controllers/SubscriptionControllerSpec.scala
- test/controllers/auth/AtedSubscriptionAuthHelpersSpec.scala
- test/utils/AuthUtilsSpec.scala
DL-2673 added unauthorised agent assistant error page
**New feature** 
Added a new unauthorised page for agents with an assistant enrolment. 
*Reviewee* (David Thornton)
> DL-2673 added unauthorised agent assistant error page

- app/connectors/AtedSubscriptionConnector.scala
Url update as part of self heal.
> DL-2695-url: Updated url for etmp check

- app/connectors/AtedSubscriptionConnector.scala
- app/controllers/RegisteredBusinessController.scala
- app/controllers/auth/AuthFunctionality.scala
- app/models/AtedSubscriptionAuthData.scala
- app/models/EtmpModels.scala
- app/services/EtmpCheckService.scala
- app/services/RegisterUserService.scala
- it/helpers/application/IntegrationApplication.scala
- test/builders/AuthBuilder.scala
- test/connectors/AtedSubscriptionConnectorSpec.scala
- test/controllers/RegisteredBusinessControllerSpec.scala
- test/controllers/auth/AtedSubscriptionAuthHelpersSpec.scala
- test/controllers/auth/AuthFunctionalitySpec.scala
- test/services/EtmpCheckServiceSpec.scala
**Self-heal tweaks**
* Added ES8 call to tax-enrolments upon self-heal success
> DL-2782 Self-heal ES8 check

- app/views/atedMain.scala.html
- app/views/atedNoAuthMain.scala.html
- app/views/subscription.scala.html
- project/FrontendBuild.scala
- project/plugins.sbt
- public/stylesheets/focus.css
- public/stylesheets/palette.css
DL-2980: Added focus and palette css files for accessibility
*Reviewer* (Paul Anderson)
> DL-2980: Added focus and palette css files for accessibility

- app/views/contactDetails.scala.html
DL-2890: Added class to button on contact details
> DL-2890: Added class to button on contact details

- app/services/RegisterUserService.scala
- conf/application.conf
- it/helpers/LoginStub.scala
- it/helpers/application/IntegrationApplication.scala
- test/builders/SessionBuilder.scala
- test/controllers/ApplicationControllerSpec.scala
- test/controllers/ContactDetailsControllerSpec.scala
- test/controllers/ContactDetailsEmailControllerSpec.scala
- test/controllers/nonUKReg/DeclarationControllerSpec.scala
DL-4064: Update application.conf
Bug fix
DL-4064: Update application.conf
> DL-4064: Update application.conf

- conf/logback-test.xml
DL-4078: Update logging config
*Reviewee* (Nadin)
*Reviewer* (Marjan)
> DL-4078: Update logging config

- conf/application.conf
- project/AppDependencies.scala
DL-4212 implement accessibility statement
**Accessibility**
> DL-4212 implement accessibility statement

- test/controllers/ReviewBusinessDetailsControllerSpec.scala
DL-3205 Review Business Details Back Link
Added Test for Review Business Details back link
*Reviewee* (Iyke)
> DL-3205 Review Business Details Back Link

- test/controllers/CorrespondenceAddressControllerSpec.scala
- test/controllers/RegisteredBusinessControllerSpec.scala
- test/controllers/SubscriptionControllerSpec.scala
DL-3199 Back Link Tests
Added back link tests so that they can be removed from the acceptance tests
*Reviewee* (Iyke)
> DL-3199 Back Link Tests

- app/views/agentSubscription.scala.html
- app/views/appointAgent.scala.html
- app/views/contactDetailsEmail.scala.html
- app/views/helpers/atedInputRadioGroupNew.scala.html
- app/views/helpers/atedInputRadioGroupReveal.scala.html
- app/views/previous_submitted.scala.html
- app/views/registeredBusinessAddress.scala.html
- app/views/reviewBusinessDetails.scala.html
- app/views/subscription.scala.html
- conf/messages
- project/AppDependencies.scala
DL-5317 ATED subscription frontend: Remove redundant GA code
remove old GA code
> DL-5317 remove old GA code

- app/views/appointAgent.scala.html
- app/views/contactDetails.scala.html
- app/views/contactDetailsEmail.scala.html
- app/views/correspondenceAddress.scala.html
- app/views/helpers/pageHeadersAndError.scala.html
- app/views/inform.scala.html
- app/views/previous_submitted.scala.html
- app/views/registeredBusinessAddress.scala.html
- app/views/reviewBusinessDetails.scala.html
- app/views/sameAccount.scala.html
- app/views/subscription.scala.html
- conf/messages
- test/controllers/ReviewBusinessDetailsControllerSpec.scala
**Library update content tweak**
> DL-2857-b Content tweaks for govuk-frontend upgrade

- app/views/atedMain.scala.html
- app/views/layout.scala.html
- project/AppDependencies.scala
- project/plugins.sbt
DL-5803 CSS Change
**Bug fix** 
Moved stylesheet lines of code from Ated Main to Layout so that css is rendered before any html on the page.
*Iyke*
*Paul*
> DL-5803 CSS Change

- app/controllers/RegisterUserController.scala
- app/views/error_template.scala.html
- app/views/global_error.scala.html
- test/controllers/RegisterUserControllerSpec.scala
**Bug fix**
* Fix error messages on error page not showing their message content.
> DL-5450 Frontend error fix

- app/controllers/ContactDetailsController.scala
- app/controllers/ContactDetailsEmailController.scala
- app/controllers/CorrespondenceAddressController.scala
- app/controllers/PreviousSubmittedController.scala
- app/controllers/RegisterUserController.scala
- app/controllers/ReviewBusinessDetailsController.scala
- app/controllers/SameAccountController.scala
- app/controllers/SubscriptionController.scala
- app/controllers/auth/AtedSubscriptionAuthHelpers.scala
- app/controllers/auth/AuthFunctionality.scala
- app/controllers/nonUKReg/DeclarationController.scala
- app/views/layout.scala.html
- app/views/previous_submitted.scala.html
- app/views/sameAccount.scala.html
- build.sbt
- conf/application.conf
- conf/messages
- project/AppDependencies.scala
- project/plugins.sbt
- test/controllers/ContactDetailsControllerSpec.scala
- test/controllers/ContactDetailsEmailControllerSpec.scala
- test/controllers/CorrespondenceAddressControllerSpec.scala
- test/controllers/SubscriptionControllerSpec.scala
DL-5517 ATED Accessibility: Non-descriptive error handling 
Improving error messages and summaries for accessibility inline with GOV.UK guidelines
https://design-system.service.gov.uk/components/error-message/
https://design-system.service.gov.uk/components/error-summary/
Tests have been updated too
> DL-5517 ATED Accessibility: Non-descriptive error handling 

- project/AppDependencies.scala
DL-6850
**Maintenance** 
Adding scope to Test dependencies
Upgrade other dependencies to latest
*Reviewee* (Paul Anderson)
> DL-6850 apply missing test config in dependencies plus upgrades

- app/config/ApplicationConfig.scala
- app/views/layout.scala.html
- conf/application.conf
- conf/messages
**Maintenance**
Apply changes to use new hmrcReportTechnicalIssueHelper
Tidy up non used code relating to Accessibility Statement
Remove Non required imports in Layout, messages, config
*Reviewee* (Paul Anderson)
> DL-7105 upgrade to use hmrcReportTechnicalIssueHelper

- project/AppDependencies.scala
Update play-frontend-hmrc to latest
Other dependencies updates
> DL-9487 update play frontend hmrc to latest

- conf/messages
DL-9308: New wording for user-confirmation view
> DL-9308: New wording for user-confirmation view

- app/connectors/TaxEnrolmentsConnector.scala
Enhancing the log info returned
> Log failure reason for ES8 call

- app/config/ApplicationConfig.scala
- app/connectors/AtedConnector.scala
- app/controllers/RegisteredBusinessController.scala
- app/models/AtedUsers.scala
- app/views/registeredWithDifferentGG.scala.html
- conf/application.conf
- conf/messages
- test/connectors/AtedConnectorSpec.scala
- test/controllers/RegisteredBusinessControllerSpec.scala
DL-10149 How do we inform users they are signed in with the wrong account
Bug fix 
> DL-10149 How do we inform users they are signed in with the wrong account

- app/assets/javascript/show-hide-content.js
- app/views/appointAgent.scala.html
- app/views/atedMain.scala.html
- app/views/atedNoAuthMain.scala.html
- app/views/contactDetailsEmail.scala.html
- app/views/layout.scala.html
- app/views/previous_submitted.scala.html
- app/views/subscription.scala.html
Adding show content js to fix console issue 
Relocation of css and scripts into layout 
Fixes to scripts where js not required
> DL-11743 address csp console error and misc fixes

- conf/messages
> Improve error message grammar

- app/views/layout.scala.html
- conf/application.conf
- project/AppDependencies.scala
- project/plugins.sbt
> DL-12276-play-frontend and standardpage upgrade

- app/views/agentConfirmation.scala.html
- app/views/appointAgent.scala.html
- app/views/contactDetails.scala.html
- app/views/contactDetailsEmail.scala.html
- app/views/correspondenceAddress.scala.html
- app/views/inform.scala.html
- app/views/nonUKReg/confirmation.scala.html
- app/views/nonUKReg/declaration.scala.html
- app/views/previous_submitted.scala.html
- app/views/registerUserConfirmation.scala.html
- app/views/registeredBusinessAddress.scala.html
- app/views/sameAccount.scala.html
- app/views/subscription.scala.html
HTML validation showed duplicated type entry of submit, checked component and amended accordingly
> DL-13829-1: removed duplicate submit type

- app/views/layout.scala.html
- conf/application.conf
Re add gtm container detail back to application.conf
Remove non required imports in layout
> DL-14057 re-add gtm container back to conf

- app/controllers/ContactDetailsController.scala
- app/controllers/CorrespondenceAddressController.scala
- app/utils/Constants.scala
- test/controllers/ContactDetailsControllerSpec.scala
- test/controllers/CorrespondenceAddressControllerSpec.scala
- test/testHelpers/AtedTestHelper.scala
> fix(DL-14293): Backlink for client registration workflow

- app/views/contactDetails.scala.html
- app/views/contactDetailsEmail.scala.html
- app/views/correspondenceAddress.scala.html
- build.sbt
- project/AppDependencies.scala
- project/plugins.sbt
**New feature**
Enables autocomplete and inputmode attributes for few input fields
*Reviewee* (Preetam)
> feat(DL-14866): Enable autocomplete and inputmode attributes

- app/views/appointAgent.scala.html
- app/views/atedMain.scala.html
- app/views/atedNoAuthMain.scala.html
- app/views/contactDetails.scala.html
- app/views/contactDetailsEmail.scala.html
- app/views/correspondenceAddress.scala.html
- app/views/error_template.scala.html
- app/views/global_error.scala.html
- app/views/layout.scala.html
- app/views/registeredBusinessAddress.scala.html
- app/views/reviewBusinessDetails.scala.html
- project/AppDependencies.scala
- project/plugins.sbt
- test/controllers/ReviewBusinessDetailsControllerSpec.scala
- test/utils/MockFixture.scala
- test/views/AppointAgentViewTest.scala
- test/views/ContactDetailsEmailViewTest.scala
- test/views/ContactDetailsViewTest.scala
- test/views/CorrespondenceAddressViewTest.scala
- test/views/RegisteredBusinessAddressViewTest.scala
- test/views/ReviewBusinessDetailsViewTest.scala
- test/views/ViewTestFixture.scala
> DL-15365, Back Link placement fixed for 6 pages

- app/views/inform.scala.html
- app/views/nonUKReg/declaration.scala.html
- app/views/previous_submitted.scala.html
- app/views/sameAccount.scala.html
- test/views/DeclarationViewTest.scala
- test/views/InformViewTest.scala
- test/views/PreviousSubmittedViewTest.scala
- test/views/SameAccountViewTest.scala
> DL-15403: Moved all the links outside main

- app/controllers/AgentConfirmationController.scala
- project/AppDependencies.scala
- project/build.properties
- test/controllers/AgentConfirmationControllerSpec.scala
> DL-16113, Fix for scala match error in agent confirmation

- app/forms/AtedForms.scala
- app/utils/AtedSubscriptionUtils.scala
- project/AppDependencies.scala
- test/controllers/CorrespondenceAddressControllerSpec.scala
> Users can input postcodes with special characters which would be form
